### PR TITLE
Fixed issue with creating fact from act / duty

### PR DESCRIPTION
**Pull request by blackstardlb**

### CODE REVIEW

**Comment by pimotte** [comment]
I'd be happy to review this, but style-wise there's not much to review, so it comes down to functionality. I'm happy to test, but can you be a little more specific as to what this PR fixed, and if there's anything beyond what you mention in the title?

**Comment by blackstardlb** [comment]
> I'd be happy to review this, but style-wise there's not much to review, so it comes down to functionality. I'm happy to test, but can you be a little more specific as to what this PR fixed, and if there's anything beyond what you mention in the title?

I added the ability to create a fact directly from the actor/action/object/recipient fields. 
Screenshot_20200622_101954

I also added the ability to run a flintmodel runner by right clicking anywhere in the runner's editor.

**Comment by pimotte** [comment]
I'm not sure if I'm doing anything wrong, but I can't get the suggestion to pop up. Is there a shortcut I need (I tried ctrl+space and alt+enter). I do get the Flint Model Runner context option, so at least I managed to compile the changes:')

**Comment by blackstardlb** [comment]
> I'm not sure if I'm doing anything wrong, but I can't get the suggestion to pop up. Is there a shortcut I need (I tried ctrl+space and alt+enter). I do get the Flint Model Runner context option, so at least I managed to compile the changes:')

You type in the name of the fact you want to make and hit ctrl+space.

**Comment by pimotte** [comment]
Nope, just getting a generic suggestion. I do also have an error, could this relate to #11 ?
Screenshot_20200624_145641

**Comment by blackstardlb** [comment]
> Nope, just getting a generic suggestion. I do also have an error, could this relate to #11 ?

I just merged in the changes from #11

**Pull request merged**
