### PR TITLE
Interpretation status

### PR DESCRIPTION
**Pull request by TristanAlbers**
- Nodes (Act/Fact/Duty) are archiveable ( this process is reversible, able to unarchive node)
- Archived nodes are in a dedicated folder in FlintView
- Nodes have versions which are updateable
- Error added for references to archived / outdated nodes in an active role
- Outdated nodes are viewable and transient
- Outdated nodes can be viewed via dropdown list
- Search scope adjusted so outdated nodes won't show in autofill
- Added translations for new menu items (Import, Export updated)
- Added checkboxes to track if a node is verified, validated and publicated ( Checkboxes only selectable in that specific order )
-  Updated tests
- Raised JVM memory from 512 to 1024 for memory intensive build phase

### CODE REVIEW

**Comment by blackstardlb** [comment]
image
Casting that many times seems excessive

**Comment by blackstardlb** [comment]
image
forground color causes an error to show for some reason in VersionEditor
image
make version property not editable from the editor
image

Do we have negative versions?
image

**Comment by TristanAlbers** [comment]
Instead of a seperate boolean/flag the latest version (while switching between different versions) has a negative value, resets when the current version is selected again:

image

**Review by blackstardlb — APPROVED** [review]
lgtm :+1:

**Pull request merged**
