### PR TITLE
Tagging

### PR DESCRIPTION
**Pull request by blackstardlb**
- Added ability to tag source reference text to specify which parts of the text are the source for the property of an act/fact/duty. 
- Can now import law texts and create acts/facts/duties from them.
- Can tag source reference text with multiple roles.
- Can also create act / fact / duties from law text with Right Click.
- Auto assigns tagged words to role if the role is empty.
- Updated Docs
- Added Gradle Dependency Audit
- Bumped flint-filler to v0.0.5

### CODE REVIEW

**Comment by pimotte** [comment]
Does what it say on the tin, documentation looks good.

Couple questions:

- Does it make sense to get some more interaction with the actual facts? I was expecting "tagging as actor" to also make the actor that tag. Maybe that's a little bit too eager, but having some quick-fix option to do that might be nice? If yes, I propose we leave this to a future feature, we can merge this as is.
- It appears overlapping tags are not a thing. I get that's gonna be kind of messy given the way you're displaying it, but I would guess a tag for the name might very well overlap with actor and object. Is this a blocker? If not, I'm good with merging this.

**Review by pimotte — APPROVED** [review]

**Comment by pimotte** [comment]
LGTM. Clean solution to the multiple tags problem. Docs are up to date, functionality works.

Couple questions, remarks:
- Do the coloured squares still mean anything? Iirc they used to be for the tags, but I'm not seeing the colours come back anywhere. It might make sense to highlight the text in the source in the relevant colour when selecting said action?
- Since the flintfiller uses the verbatim text, does it make sense to include the tags by default? Don't know how much work this is.

Both of these could be included in a later PR, just nice to have.

**Review by pimotte — APPROVED** [review]

**Comment by blackstardlb** [comment]
> * Do the coloured squares still mean anything? Iirc they used to be for the tags, but I'm not seeing the colours come back anywhere. It might make sense to highlight the text in the source in the relevant colour when selecting said action?
Good point. I discussed  with Robert and we decided that colors are a bad idea. (Color blind people and doesn't work with multi tagging). So i'll be removing those boxes.
> * Since the flintfiller uses the verbatim text, does it make sense to include the tags by default? Don't know how much work this is.
We are hopeing to automate tagging or have tagging suggestions in the future.

I also found a bug where when creating an act/duty/fact from artikel text show the wrong artikel. (EG artikel 1 instead of artikel 2). Fix is coming

**Review by pimotte — APPROVED** [review]
Still works, LGTM:)

**Pull request merged**
